// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODataMicroservice;

namespace ODataMicroservice.Migrations
{
    [DbContext(typeof(DbDataContext))]
    [Migration("20180823123312_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ODataMicroservice.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("TemperatureReadingId");

                    b.HasKey("AlertId");

                    b.HasIndex("TemperatureReadingId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ODataMicroservice.TemperatureReading", b =>
                {
                    b.Property<int>("TemperatureReadingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("MeasureDateTime");

                    b.Property<double>("Temperature");

                    b.HasKey("TemperatureReadingId");

                    b.ToTable("TemperatureReadings");
                });

            modelBuilder.Entity("ODataMicroservice.Alert", b =>
                {
                    b.HasOne("ODataMicroservice.TemperatureReading", "TemperatureReading")
                        .WithMany()
                        .HasForeignKey("TemperatureReadingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
