queue: Hosted Linux Preview
variables:
  buildConfiguration: 'Release'
  dockerId: hackfestregistry

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/hackfest-templogger:$BUILD_BUILDID ./src
    docker tag $(dockerId).azurecr.io/hackfest-templogger:$BUILD_BUILDID $(dockerId).azurecr.io/hackfest-templogger:latest
    docker login -u $(dockerId) -p $pswd $(dockerid).azurecr.io
    docker push $(dockerId).azurecr.io/hackfest-templogger:$BUILD_BUILDID
    docker push $(dockerId).azurecr.io/hackfest-templogger:latest
  env:
    pswd: $(dockerPassword)